### ISSUE TITLE
Since update to HA 113.3 (or 114), some sort of API error in the log

### ISSUE THREAD

**Issue by v-sante** [mKeRix/hassio-repo#7]
On a configuration that was previously working perfectly, now get this in the RA logs when loading:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:20:33] ERROR: Got unexpected response from the API: Service not enabled
[10:20:33] INFO: Starting room-assistant
```

It continues to load but no data is supplied to MQTT for the various entities configured.

No errors visible in the HA system log.

Tried a full uninstall and reinstall and no change.

Configuration as follows (with addresses removed, but as mentioned working perfectly prior to a day ago):

```
global:
  instanceName: Office
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
bluetoothClassic:
  hciDeviceId: 1
  addresses:
    - '0'
bluetoothLowEnergy:
  hciDeviceId: 0
  onlyIbeacon: true
  whitelist:
    - 1
    - 2
    - 3
  tagOverrides:
    1:
      name: Postbox Beacon
    2:
      name: Collection Beacon
    3:
      name: Car Door Beacon
```

Device 1 is a bluetooth USB stick.

RPI 3B+ on fully up to date HA install.

Last note is there was a powercut yesterday, but this doesn't look like a hardware issue given the API error?
